# Generated by Django 6.1 on 2026-08-22 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('problemas', models.TextField(blank=True, null=True, verbose_name='Problemas')),
                ('analise_por_imagem', models.BooleanField(default=False, verbose_name='Análise por imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Produto ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categorias', models.ManyToManyField(blank=True, related_name='produtos', to='categorias.categoria', verbose_name='Categorias')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_agricolas', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Produto agrícola',
                'verbose_name_plural': 'Produtos agrícolas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['nome'], name='culturas_pr_nome_b3305b_idx'), models.Index(fields=['ativo'], name='culturas_pr_ativo_767e0f_idx'), models.Index(fields=['analise_por_imagem'], name='culturas_pr_analise_8ddfd0_idx'), models.Index(fields=['usuario'], name='culturas_pr_usuario_d60fe3_idx'), models.Index(fields=['-criado_em'], name='culturas_pr_criado__94ad6f_idx')],
            },
        ),
    ]
