# Generated by Django 6.0.7 on 2026-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoagricola',
            options={'ordering': ['nome'], 'verbose_name': 'Produto agrícola', 'verbose_name_plural': 'Produtos agrícolas'},
        ),
        migrations.RemoveIndex(
            model_name='produtoagricola',
            name='produtos_pr_nome_cab1b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='produtoagricola',
            name='produtos_pr_ativo_8408f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='produtoagricola',
            name='produtos_pr_analise_eb364f_idx',
        ),
        migrations.RemoveIndex(
            model_name='produtoagricola',
            name='produtos_pr_usuario_b57845_idx',
        ),
        migrations.RemoveIndex(
            model_name='produtoagricola',
            name='produtos_pr_criado__308f9f_idx',
        ),
        migrations.AlterField(
            model_name='produtoagricola',
            name='analise_por_imagem',
            field=models.BooleanField(default=True, verbose_name='Permitir análise por imagem'),
        ),
        migrations.AlterField(
            model_name='produtoagricola',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Disponível no catálogo'),
        ),
        migrations.AlterField(
            model_name='produtoagricola',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='produtoagricola',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='produtoagricola',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produtoagricola',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='produtoagricola',
            name='problemas',
            field=models.TextField(blank=True, default='', verbose_name='Problemas / doenças'),
        ),
    ]
