# Generated by Django 6.0.7 on 2026-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtoagricola_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoagricola',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='produtos/', verbose_name='Imagem'),
        ),
    ]
