# Generated by Django 6.1 on 2026-08-22 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localização')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('provincia', models.CharField(blank=True, default='Moxico', max_length=100, verbose_name='Província')),
                ('tipo_utilizador', models.CharField(choices=[('agricultor', 'Agricultor'), ('tecnico', 'Técnico Agrícola'), ('estudante', 'Estudante'), ('investigador', 'Investigador'), ('administrador', 'Administrador'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo de utilizador')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto do perfil')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
