# Generated by Django 6.0.7 on 2026-09-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nome'], name='categoria_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['ativo'], name='categoria_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['-criado_em'], name='categoria_criado_idx'),
        ),
    ]
