# Generated by Django 6.1 on 2026-08-22 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('culturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='diagnosticos/%Y/%m/%d/', verbose_name='Imagem analisada')),
                ('classe_identificada', models.CharField(blank=True, max_length=150, verbose_name='Classe identificada pela IA')),
                ('resultado', models.CharField(choices=[('saudavel', 'Saudável'), ('doenca', 'Doença'), ('praga', 'Praga'), ('fungo', 'Fungo'), ('deficiencia', 'Deficiência nutricional'), ('outro', 'Outro'), ('indeterminado', 'Indeterminado')], default='indeterminado', max_length=30, verbose_name='Resultado')),
                ('doenca_identificada', models.CharField(blank=True, max_length=200, verbose_name='Doença identificada')),
                ('confianca', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Confiança da IA (%)')),
                ('descricao_resultado', models.TextField(blank=True, verbose_name='Descrição do resultado')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Estado')),
                ('erro', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do diagnóstico')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='culturas.produtoagricola', verbose_name='Produto agrícola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
