# Generated by Django 6.0.7 on 2026-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='imagem',
            field=models.ImageField(max_length=255, upload_to='diagnosticos/%Y/%m/%d/', verbose_name='Imagem analisada'),
        ),
    ]
